pivot_columns <- c(                                   "year",                                 
"run",                                   "sex",                                  
"age",                                                           
"age20",                                                              
"dz_id",                                 "dz_name",                              
"sdz_code",                              "sdz_name",                             
"soa_code",                              "soa_name",                             
"sa_code",                               "county",                               
"PARLCON2024_code",                      "PARLCON2024_name",                     
"PARLCON2008_code",                      "PARLCON2008_name",                     
"SETTLEMENT2015_code",                   "SETTLEMENT2015_name",                  
"SETTLEMENT2015_Band",                   "LGD2014_code",                         
"LGD2014_name",                          "LGD1992_code",                         
"LGD1992_name",                          "HSCT",                                 
"DEA2014_name",                          "DEA2014_code",                         
"AA2008",                                "AA1998",                               
"NRA_name",                              "NRA_code",                             
"WARD1992",                              "Urban_status",                         
"Urban_mixed_rural_status",              "mdm_rank",                             
"mdm_quintile_soa",                      "mdm_quintile_soa_name",                
"mdm_decile_soa",                        "income_dm_rank",                       
"income_dm_quintile_soa",                "income_dm_decile_soa",                 
"employment_dm_rank",                    "employment_dm_quintile_soa",           
"employment_dm_decile_soa",              "custom_townsend_rank",                 
"custom_townsend_score_dz",              "ethnicity",                            
"broad_ethnicity",                       "stroke",                               
"chd",                                   "diabetes",                             
"dementia",                              "heart_failure",                        
"atrial_fibrillation",                   "hypertension",                         
"chronic_kidney_disease",                "lung_cancer",                          
"ethrisk",                              
"age10",                                
"bmi",                                  
"smoking",                              
"ecigarette",                            "alcohol",                              
"diet",                                  "pa",                                   
"wellbeing",                             "pm25g",                                
"sleep",                                 "cholesterol_status",                   
"hypertension_status",                   "deprivation_quintile",                 
"diabetes_status",                       "cholesterol_status_granular",          
"health",                                "loneliness",                           
"limiting",                              "disability",                           
"non_diabetic_hyperglycaemia",           "copd",                                 
"asthma",                                "depression",                           
"pad",                                   "vte",                                  
"epilepsy",                              "hypothyroidism",                       
"osteoporosis",                          "rheumatoid_arthritis",                 
"abdominal_aortic_aneurysm",             "nafld_disease",                        
"arld_disease",                          "ibd",                                  
"sle",                                   "interstitial_lung_disease",            
"osteoarthritis",                        "fracture4",                            
"nof",                                   "cervical_cancer",                      
"prostate_cancer",                       "female_breast_cancer",                 
"renal_cancer",                          "oral_cancer",                          
"pancreatic_cancer",                     "uterine_cancer",                       
"blood_cancer",                          "ovarian_cancer",                       
"brain_cancer",                          "osteogastric_cancer",                  
"cancer",                               
"blood_multiple_myeloma",                "blood_lymphoma",                       
"blood_leukaemia",                           
"nafld",                                 "arld",                                 
"ild",                                   "aortic_aneursym",                      
"inflammatory_bowel_disease"
)
