QFracture_2016_fracture4 female
/* 
 * Copyright 2016 ClinRisk Ltd.
 * 
 * This file is part of QFracture-2016 (http://qfracture.org, http://svn.clinrisk.co.uk/qfracture).
 * 
 * QFracture-2016 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QFracture-2016 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with QFracture-2016.  If not, see http://www.gnu.org/licenses.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/qfracture, faithfully implements QFracture-2016.
 *   We have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally 
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same 
 *   results as the original code posted at http://svn.clinrisk.co.uk/qfracture.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 *
 * End of additional terms
 * 
 * This file has been auto-generated.
 * XML source: QFracture_2016_fracture4_0.xml
 * STATA dta time stamp: 4 Jan 2016 10:50
 * This file was created on: Tue 27 Sep 2016 15:18:00 BST
 */

static double fracture4_female_raw(
    int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_corticosteroids,int b_cvd,int b_dementia,int b_endocrine,int b_epilepsy2,int b_falls,int b_hrt_oest,int b_liver,int b_malabsorption,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int fh_osteoporosis,int smoke_cat,int surv
)
{
  double survivor[11] = {
    0,
    0.998549282550812,
    0.996993362903595,
    0.995339095592499,
    0.993514478206635,
    0.991504669189453,
    0.989245474338531,
    0.986799359321594,
    0.984268248081207,
    0.981499433517456,
    0.978452086448669
  };
  
  /* The conditional arrays */
  
  double Ialcohol[6] = {
    0,
    -0.0161196598427115580000000,
    0.0181421919546882990000000,
    0.0870398130913111050000000,
    0.4850876681648371200000000,
    0.4521470045723863200000000
  };
  double Iethrisk[10] = {
    0,
    0,
    -0.4256606921636625400000000,
    -0.5543209119502141600000000,
    -0.9182601097806930600000000,
    -0.6819360653148304200000000,
    -1.4668483404988077000000000,
    -0.9101238114228446000000000,
    -0.6421783317544739200000000,
    -0.5036829432634510900000000
  };
  double Ismoke[5] = {
    0,
    0.0557356934305611660000000,
    0.1633895661701352800000000,
    0.1540488338696587000000000,
    0.2329771591757904500000000
  };
  
  /* Applying the fractional polynomial transforms */
  /* (which includes scaling)                      */
  
  double dage = age;
  dage=dage/10;
  double age_1 = pow(dage,2);
  double age_2 = pow(dage,3);
  double dbmi = bmi;
  dbmi=dbmi/10;
  double bmi_1 = pow(dbmi,-1);
  
  /* Centring the continuous variables */
  
  age_1 = age_1 - 25.463895797729492;
  age_2 = age_2 - 128.495315551757810;
  bmi_1 = bmi_1 - 0.382189363241196;
  
  /* Start of Sum */
  double a=0;
  
  /* The conditional sums */
  
  a += Ialcohol[alcohol_cat6];
  a += Iethrisk[ethrisk];
  a += Ismoke[smoke_cat];
  
  /* Sum from continuous values */
  
  a += age_1 * 0.1488230617216508300000000;
  a += age_2 * -0.0095516624764288762000000;
  a += bmi_1 * 2.8180291389827810000000000;
  
  /* Sum from boolean values */
  
  a += b_antidepressant * 0.2935891578881283900000000;
  a += b_anycancer * 0.1175522733147793100000000;
  a += b_asthmacopd * 0.1997193753352899900000000;
  a += b_corticosteroids * 0.2187020094246774900000000;
  a += b_cvd * 0.1419643725503051700000000;
  a += b_dementia * 0.4697387263085152100000000;
  a += b_endocrine * 0.1105394028217592300000000;
  a += b_epilepsy2 * 0.4024460098604033000000000;
  a += b_falls * 0.3322321626303583700000000;
  a += b_hrt_oest * -0.2027864456358232400000000;
  a += b_liver * 0.4831161576961586200000000;
  a += b_malabsorption * 0.1687477801835574600000000;
  a += b_parkinsons * 0.4742239358039181400000000;
  a += b_ra_sle * 0.2267059327471904200000000;
  a += b_renal * 0.2508648723794006400000000;
  a += b_type1 * 0.7832887160932293600000000;
  a += b_type2 * 0.2363869657814060800000000;
  a += fh_osteoporosis * 0.3837949755860494700000000;
  
  /* Sum from interaction terms */
  
  
  /* Calculate the score itself */
  double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
  return score;
}
QFracture_2016_fracture4 male
/* 
 * Copyright 2016 ClinRisk Ltd.
 * 
 * This file is part of QFracture-2016 (http://qfracture.org, http://svn.clinrisk.co.uk/qfracture).
 * 
 * QFracture-2016 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QFracture-2016 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with QFracture-2016.  If not, see http://www.gnu.org/licenses.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/qfracture, faithfully implements QFracture-2016.
 *   We have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally 
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same 
 *   results as the original code posted at http://svn.clinrisk.co.uk/qfracture.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * End of additional terms
 * 
 * This file has been auto-generated.
 * XML source: QFracture_2016_fracture4_1.xml
 * STATA dta time stamp: 4 Jan 2016 10:50
 * This file was created on: Tue 27 Sep 2016 15:19:05 BST
 */

static double fracture4_male_raw(
    int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_carehome,int b_corticosteroids,int b_cvd,int b_dementia,int b_epilepsy2,int b_falls,int b_liver,int b_malabsorption,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int fh_osteoporosis,int smoke_cat,int surv
)
{
  double survivor[11] = {
    0,
    0.999435424804688,
    0.998826444149017,
    0.998191893100739,
    0.997505903244019,
    0.996722519397736,
    0.995886385440826,
    0.994963765144348,
    0.993958413600922,
    0.992862939834595,
    0.991695225238800
  };
  
  /* The conditional arrays */
  
  double Ialcohol[6] = {
    0,
    -0.1129648713412066400000000,
    -0.1019933147383609900000000,
    -0.0087172177838055233000000,
    0.2378367291894386800000000,
    0.5900674828324269400000000
  };
  
  double Iethrisk[10] = {
    0,
    0,
    -0.2497759361694920600000000,
    -0.3388723409363771900000000,
    -1.1780652312756217000000000,
    -0.5637536128417445200000000,
    -0.8802674221403056200000000,
    -0.6220839068056021000000000,
    -0.8700240760084387800000000,
    -0.3586934603990843400000000
  };
  double Ismoke[5] = {
    0,
    0.0374622547112923930000000,
    0.2536654624283247200000000,
    0.2728541689904917000000000,
    0.3498259780437700300000000
  };
  
  /* Applying the fractional polynomial transforms */
  /* (which includes scaling)                      */
  
  double dage = age;
  dage=dage/10;
  double age_2 = dage;
  double age_1 = pow(dage,0.5);
  double dbmi = bmi;
  dbmi=dbmi/10;
  double bmi_2 = pow(dbmi,-0.5);
  double bmi_1 = pow(dbmi,-1);
  
  /* Centring the continuous variables */
  
  age_1 = age_1 - 2.201908826828003;
  age_2 = age_2 - 4.848402023315430;
  bmi_1 = bmi_1 - 0.375702142715454;
  bmi_2 = bmi_2 - 0.612945437431335;
  
  /* Start of Sum */
  double a=0;
  
  /* The conditional sums */
  
  a += Ialcohol[alcohol_cat6];
  a += Iethrisk[ethrisk];
  a += Ismoke[smoke_cat];
  
  /* Sum from continuous values */
  
  a += age_1 * -8.5962113395742179000000000;
  a += age_2 * 2.3534585567599957000000000;
  a += bmi_1 * 18.3534753639015770000000000;
  a += bmi_2 * -19.0905273467733320000000000;
  
  /* Sum from boolean values */
  
  a += b_antidepressant * 0.4185009802564456600000000;
  a += b_anycancer * 0.2923849667849617900000000;
  a += b_asthmacopd * 0.2658243150152003200000000;
  a += b_carehome * 0.0946727309614458920000000;
  a += b_corticosteroids * 0.2601592893954755000000000;
  a += b_cvd * 0.2155420976820900700000000;
  a += b_dementia * 0.6253066390475994200000000;
  a += b_epilepsy2 * 0.6695708064301426600000000;
  a += b_falls * 0.4477141342626502200000000;
  a += b_liver * 0.7970936081024936300000000;
  a += b_malabsorption * 0.2508921035498924400000000;
  a += b_parkinsons * 0.8254276340218873500000000;
  a += b_ra_sle * 0.3846585832735093200000000;
  a += b_renal * 0.4479672880062486300000000;
  a += b_type1 * 1.0121689145067305000000000;
  a += b_type2 * 0.2439254432490279300000000;
  a += fh_osteoporosis * 0.9898717512466593800000000;
  
  /* Sum from interaction terms */
  
  
  /* Calculate the score itself */
  double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
  return score;
}
QFracture_2016_nof female
/* 
 * Copyright 2016 ClinRisk Ltd.
 * 
 * This file is part of QFracture (http://qfracture.org, http://svn.clinrisk.co.uk/opensource/qfracture).
 * 
 * QFracture is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QFracture is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with QFracture-2016.  If not, see http://www.gnu.org/licenses.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qfracture, faithfully implements QFracture.
 *   We have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally 
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same 
 *   results as the original code posted at http://svn.clinrisk.co.uk/opensource/qfracture.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * End of additional terms
 *
 * This file has been auto-generated.
 * XML source: QFracture_2016_nof_0.xml
 * STATA dta time stamp: 4 Jan 2016 10:50
 * This file was created on: Tue 27 Sep 2016 18:11:05 BST
 */

static double nof_female_raw(
    int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_corticosteroids,int b_cvd,int b_dementia,int b_endocrine,int b_epilepsy2,int b_falls,int b_fracture4,int b_hrt_oest,int b_liver,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int smoke_cat,int surv
)
{
  double survivor[11] = {
    0,
    0.999798893928528,
    0.999581158161163,
    0.999346554279327,
    0.999083101749420,
    0.998790085315704,
    0.998455047607422,
    0.998097419738770,
    0.997704565525055,
    0.997259438037872,
    0.996739983558655
  };
  
  /* The conditional arrays */
  
  double Ialcohol[6] = {
    0,
    -0.1261758201330289700000000,
    -0.1373243347908413300000000,
    -0.1133616834893930700000000,
    0.4017887033571813100000000,
    0.5006572131880983000000000
  };
  double Iethrisk[10] = {
    0,
    0,
    -0.5210282168631360500000000,
    -0.4177942104837170100000000,
    -0.7951236994041091000000000,
    -0.6588104797725504700000000,
    -1.5796225547799494000000000,
    -1.0777580735638324000000000,
    -0.8521785631761629200000000,
    -0.5715035184075031300000000
  };
  double Ismoke[5] = {
    0,
    0.0294188680292629120000000,
    0.3263756428320784300000000,
    0.3496437278702089800000000,
    0.5155176914691816900000000
  };
  
  /* Applying the fractional polynomial transforms */
  /* (which includes scaling)                      */
  
  double dage = age;
  dage=dage/10;
  double age_1 = pow(dage,2);
  double age_2 = pow(dage,3);
  double dbmi = bmi;
  dbmi=dbmi/10;
  double bmi_1 = pow(dbmi,-2);
  
  /* Centring the continuous variables */
  
  age_1 = age_1 - 25.815217971801758;
  age_2 = age_2 - 131.163711547851560;
  bmi_1 = bmi_1 - 0.146003782749176;
  
  /* Start of Sum */
  double a=0;
  
  /* The conditional sums */
  
  a += Ialcohol[alcohol_cat6];
  a += Iethrisk[ethrisk];
  a += Ismoke[smoke_cat];
  
  /* Sum from continuous values */
  
  a += age_1 * 0.2600550792365882700000000;
  a += age_2 * -0.0171243805014380560000000;
  a += bmi_1 * 5.2078461133313851000000000;
  
  /* Sum from boolean values */
  
  a += b_antidepressant * 0.2961370228136101500000000;
  a += b_anycancer * 0.1141350453612936500000000;
  a += b_asthmacopd * 0.1458646814083802100000000;
  a += b_corticosteroids * 0.1780165520696634900000000;
  a += b_cvd * 0.1386725900431314300000000;
  a += b_dementia * 0.5593392615149843600000000;
  a += b_endocrine * 0.1988932345923676800000000;
  a += b_epilepsy2 * 0.4544705186649458100000000;
  a += b_falls * 0.2682716649575493400000000;
  a += b_fracture4 * 0.4485906129569035000000000;
  a += b_hrt_oest * -0.2585315313281359400000000;
  a += b_liver * 0.4764394125573222500000000;
  a += b_parkinsons * 0.5444815361802923800000000;
  a += b_ra_sle * 0.3084108024586954500000000;
  a += b_renal * 0.2487817440674148200000000;
  a += b_type1 * 1.3350155588126134000000000;
  a += b_type2 * 0.4128514481325198400000000;
  
  /* Sum from interaction terms */
  
  
  /* Calculate the score itself */
  double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
  return score;
}
QFracture_2016_nof male
/* 
 * Copyright 2016 ClinRisk Ltd.
 * 
 * This file is part of QFracture (http://qfracture.org, http://svn.clinrisk.co.uk/opensource/qfracture).
 * 
 * QFracture is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QFracture is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with QFracture-2016.  If not, see http://www.gnu.org/licenses.
 * 
 * Additional terms
 * 
 * The following disclaimer must be displayed alongside any risk score generated by this code.
 *   The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qfracture, faithfully implements QFracture.
 *   We have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally 
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   We stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same 
 *   results as the original code posted at http://svn.clinrisk.co.uk/opensource/qfracture.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 * 
 * End of additional terms
 *
 * This file has been auto-generated.
 * XML source: QFracture_2016_nof_1.xml
 * STATA dta time stamp: 4 Jan 2016 10:50
 * This file was created on: Tue 27 Sep 2016 18:11:52 BST
 */

static double nof_male_raw(
    int age,int alcohol_cat6,int b_antidepressant,int b_anycancer,int b_asthmacopd,int b_carehome,int b_corticosteroids,int b_cvd,int b_dementia,int b_epilepsy2,int b_falls,int b_fracture4,int b_liver,int b_parkinsons,int b_ra_sle,int b_renal,int b_type1,int b_type2,double bmi,int ethrisk,int fh_osteoporosis,int smoke_cat,int surv
)
{
  double survivor[11] = {
    0,
    0.999893844127655,
    0.999774158000946,
    0.999640882015228,
    0.999497473239899,
    0.999327778816223,
    0.999136328697205,
    0.998924136161804,
    0.998683452606201,
    0.998405933380127,
    0.998105704784393
  };
  
  /* The conditional arrays */
  
  double Ialcohol[6] = {
    0,
    -0.1989277879915676800000000,
    -0.2613512785873652300000000,
    -0.2165261229261542800000000,
    0.0771682474573718860000000,
    0.4865889592245968300000000
  };
  double Iethrisk[10] = {
    0,
    0,
    -0.5197707213726646700000000,
    -0.4273622890290790200000000,
    -1.3616785101903839000000000,
    -0.8979303273750973700000000,
    -0.9201178622676105000000000,
    -0.5850249719802090900000000,
    -1.2625832440588742000000000,
    -0.3934722541162818400000000
  };
  double Ismoke[5] = {
    0,
    0.0172107719322296650000000,
    0.4334014580484051300000000,
    0.4706305455101631500000000,
    0.6359078620828390000000000
  };
  
  /* Applying the fractional polynomial transforms */
  /* (which includes scaling)                      */
  
  double dage = age;
  dage=dage/10;
  double age_1 = pow(dage,3);
  double age_2 = pow(dage,3)*log(dage);
  double dbmi = bmi;
  dbmi=dbmi/10;
  double bmi_1 = pow(dbmi,-2);
  
  /* Centring the continuous variables */
  
  age_1 = age_1 - 113.993118286132810;
  age_2 = age_2 - 179.962387084960940;
  bmi_1 = bmi_1 - 0.141164988279343;
  
  /* Start of Sum */
  double a=0;
  
  /* The conditional sums */
  
  a += Ialcohol[alcohol_cat6];
  a += Iethrisk[ethrisk];
  a += Ismoke[smoke_cat];
  
  /* Sum from continuous values */
  
  a += age_1 * 0.0419825595398811420000000;
  a += age_2 * -0.0152519952339723320000000;
  a += bmi_1 * 5.7167542710069563000000000;
  
  /* Sum from boolean values */
  
  a += b_antidepressant * 0.4267786880099018700000000;
  a += b_anycancer * 0.2328499751645417800000000;
  a += b_asthmacopd * 0.2348015554978777900000000;
  a += b_carehome * 0.1879003102725514400000000;
  a += b_corticosteroids * 0.1740108568014504500000000;
  a += b_cvd * 0.2376902595200354700000000;
  a += b_dementia * 0.8464083378165536700000000;
  a += b_epilepsy2 * 0.7023595003140320500000000;
  a += b_falls * 0.3461048734913962900000000;
  a += b_fracture4 * 0.6405104279877627000000000;
  a += b_liver * 0.8355037910863250000000000;
  a += b_parkinsons * 0.9880686646887743000000000;
  a += b_ra_sle * 0.4201341417376428000000000;
  a += b_renal * 0.5718927887809727200000000;
  a += b_type1 * 1.3669282519025776000000000;
  a += b_type2 * 0.3057043662392859300000000;
  a += fh_osteoporosis * 0.2733760510310951400000000;
  
  /* Sum from interaction terms */
  
  
  /* Calculate the score itself */
  double score = 100.0 * (1 - pow(survivor[surv], exp(a)) );
  return score;
}